#!/usr/bin/env bash
# This script configures Nginx for redirection

# Check if Nginx is installed
if [ ! -x "$(command -v nginx)" ]; then
    echo "Nginx is not installed. Please run 1-install_nginx_web_server first."
    exit 1
fi

# Create a backup of the default Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Configure Nginx for redirection
sed -i '/server_name _;/a \
        location \/redirect_me { \
            return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4; \
        }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

# Display success message
echo "Nginx configured for redirection. /redirect_me now redirects to https://www.youtube.com/watch?v=QH2-TGUlwu4."
