#!/usr/bin/env bash
# This script configures Nginx for a custom 404 page

# Check if Nginx is installed
if [ ! -x "$(command -v nginx)" ]; then
    echo "Nginx is not installed. Please run 1-install_nginx_web_server first."
    exit 1
fi

# Create a backup of the default Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Configure Nginx for custom 404 page
sed -i '/server_name _;/a \
        error_page 404 /404.html;' /etc/nginx/sites-available/default

echo '<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n\'est pas une page</h1>
    <p>This is a custom 404 page.</p>
</body>
</html>' | tee /usr/share/nginx/html/404.html > /dev/null

# Restart Nginx to apply changes
service nginx restart

# Display success message
echo "Nginx configured for custom 404 page. Accessing a non-existent page will return a 404 error with the message 'Ceci n'est pas une page.'"
