#!/usr/bin/env bash

#configuring HAProxy load balancer

#update the package list 
sudo apt-get -y update

# install required packages
sudo apt-get -y install software-properties-common

# Add the HAProxy repository and install HAProxy 2.0
#sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
#sudo apt-get -y update
sudo apt-get -y install haproxy

# HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 225787-web-01 100.26.121.38:80 check
    server 225787-web-02 54.90.47.134:80 check
   "
# Add your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Start the HAProxy service
sudo service haproxy start

