#!/usr/bin/env bash
# This script displays numbers from 1 to 100 with Fizz, Buzz, and FizzBuzz substitutions

for number in {1..100}
do
    if [ $((number % 3)) -eq 0 ] && [ $((number % 5)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((number % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((number % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$number"
    fi
done
