#!/usr/bin/env bash
# Script creates an RSA key pair with a passphrase

ssh-keygen -t rsa -b 4096 -f school -N betty

# Displays key information

echo "Generating public/private rsa key pair."
echo "Your identification has been saved in school."
echo "Your public key has been saved in school.pub."
echo "The key fingerprint is:"
ssh-keygen -lf school
