#!/usr/bin/env bash
# This script creates an RSA key pair

ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N betty

# Displaying information about the created key pair
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in school."
echo "Your public key has been saved in school.pub."
echo "The key fingerprint is:"
ssh-keygen -lf ~/.ssh/school
